### PR TITLE
Bump SDL2 to 2.30.1

### PR DESCRIPTION
**Pull request by runlevel5**
To bump this lib to latest v2

### CODE REVIEW

**Comment by apanteleev** [comment]
It's odd but I'm getting many errors building with the new version of SDL2 with Visual Studio Code (VS2022 tools and Ninja).
With regular VS2022, it compiles OK.

[pr-394-log.txt](https://github.com/NVIDIA/Q2RTX/files/14829724/pr-394-log.txt)

**Comment by runlevel5** [comment]
@apanteleev is there a pipeline that I could use to reproduce the error?

**Comment by apanteleev** [comment]
No, I don't have a CI pipeline like that. Just install VS Code and CMake Tools extension, configure and build.

**Comment by runlevel5** [comment]
@apanteleev were you using clang or GCC?

**Comment by apanteleev** [comment]
MSVC from Visual Studio 2022

**Comment by res2k** [comment]
@apanteleev Did you clean your build directory?
In the past, that fixed some weird SDL compilation issues for me after updating it.
(I think something, config header or so, isn't correctly updated/regenerated if you keep build files from previous versions.)

**Comment by apanteleev** [comment]
@res2k Good suggestion! I did a clean build but didn't delete the build directory. Deleting the entire build directory fixes the errors.
Merging in a minute...

**Pull request merged**
