### PR TITLE
Add SPDX License Identifier

### PR DESCRIPTION
**Pull request by EwoutH**
Added SPDX License Identifier compliant to https://spdx.org/ids-how

### CODE REVIEW

**Comment by apanteleev** [comment]
Thank you for the contribution. I don't mind merging it, but could you please clean up the commit to avoid changing random whitespace?
Also, why do you think that these identifiers are necessary?

**Comment by EwoutH** [comment]
A SPDX identifier makes the license precise, concise and travels with files, which can be an advantage since this is the RTX version is licensed differently from the original version and it's game data.

My text editor removes trailing white spaces by default. Shall I open a separate PR for the trailing whitespaces?

**Comment by apanteleev** [comment]
Concise - yes, but the existing license plaques in every file cover all other aspects that you mentioned. And the license type is stated right there in the first paragraph of the plaque, after the new SPDX header. Besides, this project is not licensed differently from the original Quake 2, Q2PRO, or Q2VKPT: all use GPLv2.

**Comment by apanteleev** [comment]
Old and unnecessary PR, closing.

**Pull request closed without merging**
