### PR TITLE
Added support for Ground Zero and Reckoning expansion packs

### PR DESCRIPTION
**Pull request by SkacikPL**
### Code taken from Yamagi Quake 2, included slight alterations necessary for compatibility with Q2Pro client base.

Commits list is faux as i had to backtrack to fork base to match it and then just include the expansions.
This pull requests only includes following commits:

- **063d97a** (Add Ground Zero code) [src/rogue]
- **aa14268** (Add Reckoning code) [src/xatrix]
- **f5c8232** (Update CMakeLists.txt for Ground Zero & Reckoning) [_Accidentally changed wrong file_]
- **2517a77** (Fix change for wrong CMakeLists.txt file) [_Accidentally changed wrong file_]
- **2acc64a** (Update CMakeLists.txt for Ground Zero & Reckoning) 

Obviously this is just code compatibility so that new enemies/weapons/entities and their logic function correctly, appropriate textures/materials/light definitions would still need to be done.
It may also be worthy to note that by default there are lots of really dark areas in the expansions (at least without material/light definitions) so flares are unlimited by default in expansions code. It might be more viable for the player to have a flashlight (feature in my fork - can PR if needed).

Generated solution now splits projects into:
- gamex86_baseq2 (Base game)
- gamex86_xatrix (Reckoning)
- gamex86_rogue (Ground Zero)

Code is sourced from Yamagi Quake 2 [xatrix](https://github.com/yquake2/xatrix) and [rogue](https://github.com/yquake2/rogue).

_Personal fork also has a C# WPF launcher application ([provided in releases](https://github.com/SkacikPL/Q2RTX/releases)) that replaces q2rtx.exe (whist game executable is built as q2rtxgame.exe). It allows for selection between launching base game, Ground Zero, Reckoning as well as a toggle for booting game with RTX or OGL renderer. If need be i can provide it with source code.
**Preview:**
[Image](https://i.imgur.com/oJy5ktK.png)
[Video](https://streamable.com/rjhj4)_

### CODE REVIEW

**Comment by apanteleev** [comment]
Thank you for the contribution!
However, upon consulting with the legal team, given the ambiguity of the license behind the gameplay code for Ground Zero and The Reckoning, we unfortunately cannot accept this merge request.

**Comment by SkacikPL** [comment]
I assume right now Bethesda is the sole owner of rights for Quake 2 and its expansions?
Perhaps it's worth to inquire them?

Xatrix/gray matter interactive ceased operations in 2005 so it's highly unlikely anyone but Bethesda has rights to it at this point.
Rogue entertainment is still around so Ground Zero may be more problematic i imagine.

**Comment by CKWarner** [comment]
You aren't distributing anything from either Ground Zero or The Reckoning.

The assets are provided by the user, under whichever licencing terms they have.

The code to _interpret_ those assets comes from Quake 2, Yamagi Quake, Q2Pro, Q2VKPT, and so on, which are all GPL.

Xatrix Entertainment and Rogue Entertainment don't enter into it at all.

**Comment by SkacikPL** [comment]
> You aren't distributing anything from either Ground Zero or The Reckoning.
> 
> The assets are provided by the user, under whichever licencing terms they have.
> 
> The code to _interpret_ those assets comes from Quake 2, Yamagi Quake, Q2Pro, Q2VKPT, and so on, which are all GPL.
> 
> Xatrix Entertainment and Rogue Entertainment don't enter into it at all.
> 
> You would need some modified textures for the materials and lighting, though, which would be under whichever licence you get those under.

I assume the core issue lies on the fact that source code for expansions was never released or officially released as open source (i couldn't find evidence of either happening).

I assume NVIDIA is afraid of unlikely scenario that there was some unofficial release and parts of that code are used in later source ports for the expansions.

Personally i don't find that plausible as if it was the case, someone would've raised this issue much earlier for any of those source ports.

In any other case as we both agree, this is 100% custom code that doesn't belong to creators of original expansions even if it's meant to achieve same results.

**Comment by apanteleev** [comment]
> I assume the core issue lies on the fact that source code for expansions was never released or officially released as open source (i couldn't find evidence of either happening).

Correct. Apparently, the open source expansion gameplay code was created by reverse engineering the games.

**Comment by SkacikPL** [comment]
> > I assume the core issue lies on the fact that source code for expansions was never released or officially released as open source (i couldn't find evidence of either happening).
> 
> Correct. Apparently, the open source expansion gameplay code was created by reverse engineering the games.

Which should make it possible for this PR to be merged? As far as i know this should be legally clean at this point.

**Comment by apanteleev** [comment]
No. Reverse engineering is explicitly prohibited in the original game licenses. At this point, probably neither Rogue nor Xatrix (in whichever form they are now) would care, but we're trying to play it safe.

**Comment by SkacikPL** [comment]
Well then i assume we can assume this topic is now exhausted.

**Comment by Paril** [comment]
Both the Xatrix and Rogue code were indeed officially released/GPL'd by their owners. xsrc.exe and rsrc.exe were self-extracting zips put out by id back in the day, and since they all have the GPL headers it's assumed that they were GPL'd under the same license that the original game DLL was.

**Comment by Calinou** [comment]
The addons' code is GPL now:

- https://github.com/yquake2/xatrix/blob/master/LICENSE
- https://github.com/yquake2/rogue/blob/master/LICENSE

Note that a few commits were reverted in the process, since one of the contributors didn't agree to the GPL relicense.

**Pull request closed without merging**
